version: '3'

services:
  app:
    container_name: ecommerce_api_dev
    command: 'npm run start:dev'
    environment:
      - DB_HOST=db
      - DB_PORT=$DB_PORT
  db:
    container_name: ecommerce_db_dev
